services:
  - type: web
    name: onedw-backend
    runtime: python
    rootDir: backend
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: APP_NAME
        value: OneDW API
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: json
      - key: API_V1_PREFIX
        value: /api/v1
      - key: MONGODB_URL
        value: mongodb+srv://mkkarunagaran3_db_user:inf7YuvpTmvA9RuR@onedwcluster.pdn7gvb.mongodb.net/onedw?retryWrites=true&w=majority&appName=onedwCluster
      - key: MONGODB_DB_NAME
        value: onedw
      - key: SECRET_KEY
        value: onedw-production-secret-key-2024-xK9mP2qR7vL5nJ8wA3tY6uI1oE4sD0hF
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: CORS_ORIGINS
        value: '["*"]'
      - key: CORS_ALLOW_CREDENTIALS
        value: "True"
      - key: CORS_ALLOW_METHODS
        value: '["*"]'
      - key: CORS_ALLOW_HEADERS
        value: '["*"]'
      - key: SOCKETIO_CORS_ORIGINS
        value: '["*"]'
      - key: AI_MODEL
        value: openai/gpt-4o-mini
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: UPLOAD_DIR
        value: uploads
