export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000';
export const API_PREFIX = '/api/v1';

export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyOtp: '/auth/verify-otp',
    resendOtp: '/auth/resend-otp',
    me: '/users/me',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
  },
  workers: {
    list: '/workers',
    detail: (id: string) => `/workers/${id}`,
    nearby: '/workers/nearby',
    trending: '/workers/trending',
    recommended: '/workers/recommended',
    reviews: (id: string) => `/workers/${id}/reviews`,
    favorite: (id: string) => `/workers/${id}/favorite`,
  },
  services: {
    list: '/services',
    detail: (id: string) => `/services/${id}`,
    recommended: '/services/recommended',
    favorite: (id: string) => `/services/${id}/favorite`,
  },
  categories: {
    list: '/categories',
    detail: (id: string) => `/categories/${id}`,
  },
  bookings: {
    list: '/bookings',
    detail: (id: string) => `/bookings/${id}`,
    create: '/bookings',
    update: (id: string) => `/bookings/${id}`,
    cancel: (id: string) => `/bookings/${id}/cancel`,
    remove: (id: string) => `/bookings/${id}`,
    upcoming: '/bookings/upcoming',
    recent: '/bookings/recent',
  },
  reviews: {
    list: '/reviews',
    create: '/reviews',
    detail: (id: string) => `/reviews/${id}`,
  },
  wallet: {
    detail: '/wallet',
    transactions: '/wallet/transactions',
    withdraw: '/wallet/withdraw',
    addFunds: '/wallet/add',
  },
  notifications: {
    list: '/notifications',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
    remove: (id: string) => `/notifications/${id}`,
  },
  chat: {
    conversations: '/chat/conversations',
    messages: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    send: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    search: '/chat/search',
    newConversation: '/chat/conversations',
    markRead: (conversationId: string) => `/chat/conversations/${conversationId}/read`,
  },
  coupons: {
    list: '/coupons',
    validate: '/coupons/validate',
  },
  offers: {
    list: '/offers',
  },
  admin: {
    stats: '/admin/stats',
    revenue: '/admin/revenue',
    bookings: '/admin/bookings',
    booking: (id: string) => `/admin/bookings/${id}`,
    workers: '/admin/workers',
    worker: (id: string) => `/admin/workers/${id}`,
    customers: '/admin/customers',
    customer: (id: string) => `/admin/customers/${id}`,
    categories: '/admin/categories',
    category: (id: string) => `/admin/categories/${id}`,
    services: '/admin/services',
    service: (id: string) => `/admin/services/${id}`,
    coupons: '/admin/coupons',
    coupon: (id: string) => `/admin/coupons/${id}`,
    reports: '/admin/reports',
    workerApprovals: '/admin/workers/approvals',
    approveWorker: (id: string) => `/admin/workers/${id}/approve`,
    rejectWorker: (id: string) => `/admin/workers/${id}/reject`,
    complaints: '/admin/complaints',
    complaint: (id: string) => `/admin/complaints/${id}`,
    refunds: '/admin/refunds',
    refund: (id: string) => `/admin/refunds/${id}`,
  },
  search: {
    query: '/search',
    autoComplete: '/search/autocomplete',
    popular: '/search/popular',
    estimatePrice: '/search/estimate-price',
    similarWorkers: (id: string) => `/search/workers/${id}/similar`,
    similarServices: (id: string) => `/search/services/${id}/similar`,
    recentlyViewed: '/search/recently-viewed',
  },
  upload: '/uploads',
  profile: '/users/update-profile',
  faq: '/faq',
  help: '/help',
} as const;
