export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || '';
export const API_PREFIX = '/api/v1';

export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyOtp: '/auth/verify-otp',
    resendOtp: '/auth/resend-otp',
    me: '/users/me',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
  },
  workers: {
    list: '/workers',
    detail: (id: string) => `/workers/${id}`,
    nearby: '/workers/nearby',
    trending: '/workers/trending',
    recommended: '/workers/recommended',
    fastest: '/workers/fastest',
    reviews: (id: string) => `/workers/${id}/reviews`,
    favorite: (id: string) => `/workers/${id}/favorite`,
    aadhaarSubmit: '/workers/aadhaar/submit',
    aadhaarVerify: '/workers/aadhaar/verify',
    aadhaarStatus: '/workers/aadhaar/status',
  },
  verification: {
    status: '/verification/status',
    start: '/verification/start',
    documents: '/verification/documents',
    skillTestGenerate: '/verification/skill-test/generate',
    skillTestSubmit: '/verification/skill-test/submit',
    practicalSubmit: '/verification/practical/submit',
    interviewStart: '/verification/interview/start',
    interviewRespond: '/verification/interview/respond',
    transcribe: '/verification/interview/transcribe',
    complete: '/verification/complete',
    certificate: '/verification/certificate',
    verify: (certificateNo: string) => `/verification/verify/${certificateNo}`,
  },
  services: {
    list: '/services',
    detail: (id: string) => `/services/${id}`,
    recommended: '/services/recommended',
    favorite: (id: string) => `/services/${id}/favorite`,
  },
  categories: {
    list: '/categories',
    detail: (id: string) => `/categories/${id}`,
  },
  bookings: {
    list: '/bookings/my-bookings',
    detail: (id: string) => `/bookings/${id}`,
    create: '/bookings',
    updateStatus: (id: string) => `/bookings/${id}/status`,
    upcoming: '/bookings/upcoming',
    recent: '/bookings/recent',
  },
  reviews: {
    listAll: '/reviews',
    list: (workerId: string) => `/reviews/worker/${workerId}`,
    create: '/reviews',
  },
  wallet: {
    detail: '/wallet',
    transactions: '/wallet/transactions',
    withdraw: '/wallet/withdraw',
    addFunds: '/wallet/add',
  },
  notifications: {
    list: '/notifications',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
    remove: (id: string) => `/notifications/${id}`,
  },
  users: {
    search: '/users/search',
  },
  chat: {
    conversations: '/chat/conversations',
    messages: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    send: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    search: '/chat/search',
    newConversation: '/chat/conversations',
    markRead: (conversationId: string) => `/chat/conversations/${conversationId}/read`,
  },
  coupons: {
    list: '/coupons',
    validate: '/coupons/validate',
  },
  offers: {
    list: '/offers',
  },
  admin: {
    stats: '/admin/stats',
    revenue: '/admin/revenue',
    bookings: '/admin/bookings',
    booking: (id: string) => `/admin/bookings/${id}`,
    workers: '/admin/workers',
    worker: (id: string) => `/admin/workers/${id}`,
    customers: '/admin/customers',
    customer: (id: string) => `/admin/customers/${id}`,
    categories: '/admin/categories',
    category: (id: string) => `/admin/categories/${id}`,
    services: '/admin/services',
    service: (id: string) => `/admin/services/${id}`,
    coupons: '/admin/coupons',
    coupon: (id: string) => `/admin/coupons/${id}`,
    reports: '/admin/reports',
    workerApprovals: '/admin/workers/approvals',
    approveWorker: (id: string) => `/admin/workers/${id}/approve`,
    rejectWorker: (id: string) => `/admin/workers/${id}/reject`,
    workerAadhaarStatus: (id: string) => `/admin/workers/${id}/aadhaar/status`,
    verifyAadhaar: (id: string) => `/admin/workers/${id}/aadhaar/verify`,
    rejectAadhaar: (id: string) => `/admin/workers/${id}/aadhaar/reject`,
    complaints: '/admin/complaints',
    complaint: (id: string) => `/admin/complaints/${id}`,
    refunds: '/admin/refunds',
    refund: (id: string) => `/admin/refunds/${id}`,
    verificationStats: '/admin/verification/stats',
    verifications: '/admin/verification',
    verificationDetail: (id: string) => `/admin/verification/${id}`,
    approveVerification: (id: string) => `/admin/verification/${id}/approve`,
    rejectVerification: (id: string) => `/admin/verification/${id}/reject`,
    verificationNotes: (id: string) => `/admin/verification/${id}/notes`,
    verificationRetake: (id: string) => `/admin/verification/${id}/retake`,
    verificationDemoLoad: '/admin/verification/demo/load',
  },
  search: {
    query: '/search',
    autoComplete: '/search/autocomplete',
    popular: '/search/popular',
    estimatePrice: '/search/estimate-price',
    similarWorkers: (id: string) => `/search/workers/${id}/similar`,
    similarServices: (id: string) => `/search/services/${id}/similar`,
    recentlyViewed: '/search/recently-viewed',
  },
  upload: '/uploads',
  profile: '/users/update-profile',
  faq: '/faq',
  help: '/help',
  ai: {
    chat: '/ai/chat',
    history: '/ai/history',
    sessionMessages: (sessionId: string) => `/ai/history/${sessionId}`,
    deleteSession: (sessionId: string) => `/ai/history/${sessionId}`,
    serviceAssistant: '/ai/service-assistant',
    transcribe: '/ai/transcribe',
  },
  fraud: {
    analyze: '/fraud/analyze',
    report: (workerId: string) => `/fraud/report/${workerId}`,
    highRisk: '/fraud/high-risk',
    status: (workerId: string) => `/fraud/status/${workerId}`,
  },
  imageAnalysis: {
    analyze: '/ai/image-analysis',
    history: '/ai/image-analysis/history',
  },
  support: {
    contact: '/support/contact',
  },
} as const;
