export const ROUTES = {
  // public
  home: '/',
  about: '/about',
  services: '/services',
  categories: '/categories',
  categoryDetail: '/categories/:slug',
  workers: '/workers',
  search: '/search',
  workerDetail: '/workers/:id',
  help: '/help',
  faq: '/faq',
  // auth
  login: '/login',
  register: '/register',
  forgot: '/forgot-password',
  otp: '/verify-otp',
  // customer
  booking: '/book',
  bookingDetails: '/bookings/:id',
  customerDashboard: '/dashboard',
  wallet: '/wallet',
  notifications: '/notifications',
  reviews: '/reviews',
  feedback: '/bookings/:id/feedback',
  profile: '/profile',
  settings: '/settings',
  coupons: '/coupons',
  offers: '/offers',
  chat: '/chat',
  chatConversation: '/chat/:conversationId',
  // worker
  workerDashboard: '/worker/dashboard',
  // admin
  adminDashboard: '/admin',
  adminBookings: '/admin/bookings',
  adminWorkers: '/admin/workers',
  adminCustomers: '/admin/customers',
  adminCategories: '/admin/categories',
  adminServices: '/admin/services',
  adminCoupons: '/admin/coupons',
  adminReports: '/admin/reports',
  adminAnalytics: '/admin/analytics',
  workerApprovalQueue: '/admin/workers/approvals',
  complaintManagement: '/admin/complaints',
  refundRequests: '/admin/refunds',
  // 404
  notFound: '*',
} as const;

export const PROTECTED_ROUTES = [
  ROUTES.customerDashboard,
  ROUTES.workerDashboard,
  ROUTES.adminDashboard,
  ROUTES.adminBookings,
  ROUTES.adminWorkers,
  ROUTES.adminCustomers,
  ROUTES.adminCategories,
  ROUTES.adminServices,
  ROUTES.adminCoupons,
  ROUTES.adminReports,
  ROUTES.adminAnalytics,
  ROUTES.workerApprovalQueue,
  ROUTES.complaintManagement,
  ROUTES.refundRequests,
  ROUTES.booking,
  ROUTES.bookingDetails,
  ROUTES.wallet,
  ROUTES.notifications,
  ROUTES.reviews,
  ROUTES.feedback,
  ROUTES.profile,
  ROUTES.settings,
  ROUTES.coupons,
  ROUTES.offers,
  ROUTES.chat,
  ROUTES.chatConversation,
] as const;
