"""Add worker skill verification

Revision ID: bb2a990e625f
Revises: 449a80dcde76
Create Date: 2026-08-01 23:55:46.669617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2a990e625f'
down_revision: Union[str, None] = '449a80dcde76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_media', sa.JSON(), nullable=True))

    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('trust_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verification_badge', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('verification_badge')
        batch_op.drop_column('trust_score')
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('worker_verifications', schema=None) as batch_op:
        batch_op.drop_column('document_media')

    # ### end Alembic commands ###
