import type { Worker } from '@/types';

export const MOCK_WORKERS: Worker[] = [
  {
    _id: 'mock-budget-1',
    name: 'Rajesh Kumar',
    email: 'rajesh@example.com',
    role: 'worker',
    avatar: '',
    isVerified: true,
    aadhaarVerified: true,
    createdAt: '',
    updatedAt: '',
    profession: 'Electrician',
    categoryIds: [],
    bio: 'Experienced electrician with 8+ years in residential wiring.',
    experienceYears: 8,
    completedJobs: 340,
    rating: 4.2,
    reviewCount: 89,
    hourlyRate: 200,
    languages: ['Tamil', 'English'],
    skills: ['Wiring', 'Switch Repair', 'Fan Installation'],
    portfolio: [],
    certificates: [],
    coverImage: '',
    isOnline: true,
  },
  {
    _id: 'mock-fastest-1',
    name: 'Suresh Patel',
    email: 'suresh@example.com',
    role: 'worker',
    avatar: '',
    isVerified: true,
    aadhaarVerified: true,
    createdAt: '',
    updatedAt: '',
    profession: 'Plumber',
    categoryIds: [],
    bio: 'Quick and reliable plumbing services.',
    experienceYears: 5,
    completedJobs: 210,
    rating: 4.0,
    reviewCount: 67,
    hourlyRate: 250,
    languages: ['Hindi', 'English'],
    skills: ['Pipe Repair', 'Tap Installation', 'Drain Cleaning'],
    portfolio: [],
    certificates: [],
    coverImage: '',
    isOnline: true,
  },
  {
    _id: 'mock-toprated-1',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    role: 'worker',
    avatar: '',
    isVerified: true,
    aadhaarVerified: true,
    createdAt: '',
    updatedAt: '',
    profession: 'AC Technician',
    categoryIds: [],
    bio: 'Certified AC repair specialist.',
    experienceYears: 6,
    completedJobs: 450,
    rating: 4.8,
    reviewCount: 120,
    hourlyRate: 350,
    languages: ['Hindi', 'English', 'Punjabi'],
    skills: ['AC Repair', 'Gas Filling', 'Compressor Fix'],
    portfolio: [],
    certificates: [],
    coverImage: '',
    isOnline: true,
  },
  {
    _id: 'mock-budget-2',
    name: 'Venkatesh Rao',
    email: 'venkatesh@example.com',
    role: 'worker',
    avatar: '',
    isVerified: true,
    aadhaarVerified: true,
    createdAt: '',
    updatedAt: '',
    profession: 'Cleaning Professional',
    categoryIds: [],
    bio: 'Thorough home cleaning services.',
    experienceYears: 4,
    completedJobs: 180,
    rating: 4.3,
    reviewCount: 55,
    hourlyRate: 150,
    languages: ['Telugu', 'English'],
    skills: ['Deep Cleaning', 'Sofa Cleaning', 'Bathroom Scrub'],
    portfolio: [],
    certificates: [],
    coverImage: '',
    isOnline: true,
  },
  {
    _id: 'mock-fastest-2',
    name: 'Arun Prasad',
    email: 'arun@example.com',
    role: 'worker',
    avatar: '',
    isVerified: true,
    aadhaarVerified: true,
    createdAt: '',
    updatedAt: '',
    profession: 'Appliance Repair',
    categoryIds: [],
    bio: 'Fast fridge, AC and washing machine repair.',
    experienceYears: 7,
    completedJobs: 310,
    rating: 4.5,
    reviewCount: 95,
    hourlyRate: 300,
    languages: ['Tamil', 'English'],
    skills: ['Fridge Repair', 'Washing Machine', 'Microwave Fix'],
    portfolio: [],
    certificates: [],
    coverImage: '',
    isOnline: true,
  },
  {
    _id: 'mock-toprated-2',
    name: 'Meera Nair',
    email: 'meera@example.com',
    role: 'worker',
    avatar: '',
    isVerified: true,
    aadhaarVerified: true,
    createdAt: '',
    updatedAt: '',
    profession: 'Home Cleaner',
    categoryIds: [],
    bio: 'Top-rated home cleaning with eco-friendly products.',
    experienceYears: 5,
    completedJobs: 290,
    rating: 4.9,
    reviewCount: 140,
    hourlyRate: 280,
    languages: ['Malayalam', 'English'],
    skills: ['Full Home Cleaning', 'Kitchen Deep Clean', 'Eco-friendly'],
    portfolio: [],
    certificates: [],
    coverImage: '',
    isOnline: true,
  },
];
